{% set name = "vulture" %}
{% set version = "0.28" %}
{% set sha256 = "28f82ac4749a72050910f70ea250a9ab8c4f1d015197d032c773e560b868d72c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - vulture = vulture.core:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - vulture

  commands:
    - vulture --help

about:
  home: https://github.com/jendrikseipp/vulture
  license: MIT
  license_file: LICENSE.txt
  summary: 'Find dead code'

extra:
  recipe-maintainers:
    - jakirkham
