{% set name = "vulture" %}
{% set version = "1.0" %}
{% set sha256 = "4b5a8980c338e9c068d43e7164555a1e4c9c7d84961ce2bc6f3ed975f6e5bc9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - vulture = vulture.core:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - vulture

  commands:
    - vulture --help

about:
  home: https://github.com/jendrikseipp/vulture
  license: MIT
  license_file: LICENSE.txt
  summary: 'Find dead code'

extra:
  recipe-maintainers:
    - jakirkham
