# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ng1wcM0TLmjIshNWpaYY0KavCppaIlCmYRSk6LgWTnvYuyPBosg+z+w8yNoNwweEa1EJPmQf6Oz8G9y6QeYomx/yuz6ruhcl9cpBb/5bzrDmKc4KukCojnnvoe3vBK5hGZea5fV+voobyfpYPO3VwpXsmXZSdPsm/42DN6dh0qaasZUJt3TZLZ0nhr0Q9ivbDFtBkLqovgS/Pq/3BLCxv8yIcK2VKstYGSXhre/dnsAyPN0xA3CziUGiFkm37Ub5+lPhBzaL1ORk9IvVf5h2L5nq8oK4ruND33qV1wNPExLRkw0PDgxFiw/p+hIJkrm5NebUOR3vgissDRcH+RCqnrGBmLvFfOjLpdQNM3JYxkjGLVYQfjzTo9catP3q3rM33l9q0f5F5fPS2ce2/isMpPLjFP6V+hytK6WGeMe8jGEMKgkVkKqYNfAHhNf1v7Kbw+rOGpkKEq/LYPM7vPWsUk25iXiSQVvJmgCUjax+z3KuL8W3I2IBormv6HmQHc2+ZYuoHYmkVe/TZtf4dgNv7Bf5QL8JL8/ivXd3Pp2dmFcgkgR7FaEiKJWvCg1tMlkn8Vlur1gU3J5o1xN3uAfz77TW3OZn4Gxn1oafI/4gMNPj/ZAJ1PMimveCWLl/DWwYC2co4mTQ2RAkUJ6NqeOf27X6656aW6u30RW4Vui7vkg="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
