travis:
  secure:
    BINSTAR_TOKEN: f2/JrlotFKGHZiNQTyC6ZAV9i9dlUYHmK9JiT733qH5BRamuijfOOE9pJ8/12ksJtjRULUOBFQSF35b78G4WDYUYb7Bc7kjQMq6yXnHBSd0Ozv4cla5EG6JMsMvynv7sGhS+s9UILMSZI5cukMWc2kY0U75AfbIOkY4UfQo0bQHA6QJr6WiYVEjMbRDCSk8qpycpaP1KSa1p6B++Cem/bZNx5D3+3TSQQUU+kWfe8gDSPnH9WqEn3qn2p6b0WUfZD7Tt104OqGilpgwp7AixbwcyHpnlwCAK2ABRM5Bkn0BXWMnUdo2H+BJrOpmndKmCSwUkmM4VQvALLPP5wzIwBzn3HJNwOrrb/7BDHgwMlk6eoHI8iBqk1eORr10FUMq64WjJPDbk60aLX4XpVh6sWyKckEGU1uKfB2jW09jtRP1yu8C7Zjcov1DtwSfwqivwfwjX5hbJO8PADCBoIu8gFSCwYiQAjZxMhGeB/wsN85GK8AUuairA4QDvEQUSDGY6Sc6B7EXNf+GPPPK7m3Zsk20VV9w9r1PAp1X/qXwB5ijWdzvZ+YWQjVMYvU/XsGRMJTezf5EuS+H7eRhcD0xDSaxXcc20Ot/1vewUYwvJWQUut1aHB17oxK+i2yRQECdfu3oErnQ3pRyKjSw7X7DZv/mB88m+82MwIMgGkhVQO6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
