travis:
  secure:
    BINSTAR_TOKEN: Oto6qeM6lODTliGx2ov3IqW+mhkoez1vzcskL6ECFX1ScA4Sf6i8lsu3N+u7OhvM0xRqynIXQNmMFera65bfpP3QHWLjImKnmzcCrnwmV5PSoLG2B6bHubO2Re6eG0UEdm0CanFI/UwfLnvY6+FlRgYPcRBX7oKUKdYFl+v+XN+VVLiAhs8Y/nZ+zlCa/+9dET117+MW+rv3tKfAvivPWxpgbNqc4vAzGwQERfI0YKJLfjRjci2OfRq3gz2axvwsgpp7JLEH8dbHCEB3sURNY3JRuD7PzaCBBRGEPRl6Kc3hkHG2uM9yF9VOu1juoiMsb1TOgKqeHTCkuMv0tPMyRoYvTsZrhfolqKYKJ8nMOxUB+nabdcUaJhf08JrLY1UaZLg23zsf1KSgUwwOZJ8Jhn4D8bftjKVmGO1l00GEMTtO/V0b65eY9AieB5ZTuMDYIX9QPcSzZmHvgGjGJgWwcsFOPCApXQRubp5SmVMb77ozkX+oK+1z3EAiVsr6gHwduHe8Z+yQC58X5MBxBi/N/7SlejbecegDV13QZ8uyNNQH6WjU8juKS1SygZZFQYqFGmh5bYf4f8XkPdWxJNou/7GVYzLIE7noW3BvGT2yanAKtskl3KaDAHU3LmXamwDfAJzfoeNN6YDfVQ3Q2xcvGrl/LzS+PD51pUxvolnDzsA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
