travis:
  secure:
    BINSTAR_TOKEN: Ng1wcM0TLmjIshNWpaYY0KavCppaIlCmYRSk6LgWTnvYuyPBosg+z+w8yNoNwweEa1EJPmQf6Oz8G9y6QeYomx/yuz6ruhcl9cpBb/5bzrDmKc4KukCojnnvoe3vBK5hGZea5fV+voobyfpYPO3VwpXsmXZSdPsm/42DN6dh0qaasZUJt3TZLZ0nhr0Q9ivbDFtBkLqovgS/Pq/3BLCxv8yIcK2VKstYGSXhre/dnsAyPN0xA3CziUGiFkm37Ub5+lPhBzaL1ORk9IvVf5h2L5nq8oK4ruND33qV1wNPExLRkw0PDgxFiw/p+hIJkrm5NebUOR3vgissDRcH+RCqnrGBmLvFfOjLpdQNM3JYxkjGLVYQfjzTo9catP3q3rM33l9q0f5F5fPS2ce2/isMpPLjFP6V+hytK6WGeMe8jGEMKgkVkKqYNfAHhNf1v7Kbw+rOGpkKEq/LYPM7vPWsUk25iXiSQVvJmgCUjax+z3KuL8W3I2IBormv6HmQHc2+ZYuoHYmkVe/TZtf4dgNv7Bf5QL8JL8/ivXd3Pp2dmFcgkgR7FaEiKJWvCg1tMlkn8Vlur1gU3J5o1xN3uAfz77TW3OZn4Gxn1oafI/4gMNPj/ZAJ1PMimveCWLl/DWwYC2co4mTQ2RAkUJ6NqeOf27X6656aW6u30RW4Vui7vkg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
